db:
  adapter: mysql
  host: localhost
  name: flow_control_task
  user: root
  password: KENken_880929
  port: 3306

rdb:
  host: localhost
  port: 6379
  db: 0
  password:

jwt:
  secret: THISISASECRET